# B站解析开关，单独开关，受「总开关」影响
bilibilitool: true

# B站解析可选列表
bilibiliTip:
  - 提示信息
  - 简介
  - 评论图
  - 视频

# B站评论数量，设置接口返回的评论数量，范围1~无限条
bilibilinumcomments: 5

# B站推送，开启后需重启；使用[#设置B站推送+用户UID]配置推送列表
bilibilipush: false

# B站推送日志，打开或关闭定时任务日志
bilibilipushlog: true

# B站推送设置权限，(all)所有人；(admin)群主和管理员；(owner)群主；(master)主人
bilibilipushGroup: master

# B站推送表达式
bilibilipushcron: '*/10 * * * *'

# 是否发送视频动态的视频
senddynamicvideo: false

# 解析视频是否优先保内容，true为优先保证上传将使用最低分辨率，false为优先保清晰度将使用最高分辨率
videopriority: false

# 视频画质偏好设置，0 为自动根据大小选择，其他为固定画质
#  - 0: 自动根据大小选择
#  - 6: 240P 极速 (仅MP4格式支持)
#  - 16: 360P 流畅
#  - 32: 480P 清晰
#  - 64: 720P 高清 (WEB默认值)
#  - 74: 720P60 高帧率 (需登录)
#  - 80: 1080P 高清 (TV/APP默认值，需登录)
#  - 112: 1080P+ 高码率 (需大会员)
#  - 116: 1080P60 高帧率 (需大会员)
#  - 120: 4K 超清 (需大会员且支持4K)
videoQuality: 0
