# 抖音解析开关，单独开关，受「总开关」影响
douyintool: true

# 抖音解析可选
douyinTip:
  - 提示信息
  - 评论图
  - 视频
  - 背景音乐
  - 图集

# 抖音评论数量，范围1~无限条
numcomments: 5

# 发送抖音作品评论图
commentsimg: true

# 发送抖音背景音乐
detailMusic: true

# 抖音推送，开启后需重启；使用[#设置抖音推送+抖音号]配置推送列表
douyinpush: false

# 抖音推送日志，打开或关闭定时任务日志
douyinpushlog: true

# 抖音推送设置权限，(all)所有人；(admin)群主和管理员；(owner)群主；(master)主人
douyinpushGroup: master

# 抖音推送表达式
douyinpushcron: "*/10 * * * *"

# 图集BGM是否使用高清语音发送，高清语音「ios/PC」系统均无法播放，自行衡量开关（仅icqq）
sendHDrecord: true

# 抖音推送是否一同发送作品视频
senddynamicwork: false
